### ISSUE TITLE
Will not play nice with moment.js

### ISSUE THREAD

**Issue by toranb** [schickling/timemachine#3]
I found using this library along side moment.js caused some issues because we needed to ensure Date.UTC was setup also. I worked around this for now by adding this line under the line mentioned below.

https://github.com/schickling/timemachine/blob/master/src/timemachine.js#L76

```js
Date.UTC = OriginalDate.UTC;
```

Would this be something you could pull in as a formal PR? Also I assume we would need to possibly add something to the reset for this change?

**Comment by schickling** [comment]
Sorry this took so long.

**Comment by manurg** [comment]
Thanks for the fast reply!
Could you also tag a new release? That'd be great :)

**Comment by schickling** [comment]
Done.
