### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by bcowgill** [schickling/timemachine#5]
I had a look at the test plan and something didn't look right so I ran them and sure enough, failures.

Running "karma:unit" (karma) task
WARN [reporter]: Can not load "coverage", it is not registered!
  Perhaps you are missing some plugin?
WARN [preprocess]: Can not load "coverage", it is not registered!
  Perhaps you are missing some plugin?
INFO [karma]: Karma v0.12.37 server started at http://localhost:9877/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 2.1.1 (Linux 0.0.0)]: Connected on socket IEtEbgNg74KX2EKtiuQa with id 22414193
PhantomJS 2.1.1 (Linux 0.0.0) check timemachine check Date constructor should now be set to December 25, 1991 13:12:59 via dateString FAILED
	Expected 'Wed, 25 Dec 1991 13:12:59 GMT' to be 'Wed, 25 Dec 1991 12:12:59 GMT'.
	/home/me/workspace/play/timemachine/test/timemachine.js:23:50
PhantomJS 2.1.1 (Linux 0.0.0) check timemachine check Date constructor should stay the same for instantiation with dateString FAILED
	Expected 'Wed, 25 Dec 1991 13:12:59 GMT' to be 'Wed, 25 Dec 1991 12:12:59 GMT'.
	/home/me/workspace/play/timemachine/test/timemachine.js:38:78
PhantomJS 2.1.1 (Linux 0.0.0) check timemachine check Date constructor should stay the same for instantiation with year, month, day, hours, minutes, seconds, milliseconds FAILED
	Expected 'Fri, 25 Jan 1991 12:12:59 GMT' to be 'Fri, 25 Jan 1991 11:12:59 GMT'.
	/home/me/workspace/play/timemachine/test/timemachine.js:42:77
PhantomJS 2.1.1 (Linux 0.0.0): Executed 17 of 17 (3 FAILED) (0.005 secs / 0 secs)
Warning: Task "karma:unit" failed. Use --force to continue.

**Comment by bcowgill** [comment]
this test appears to have been written while BST was active, but now it isn't so the test fails. 
           expect(new Date('December 25, 1991 13:12:59').toUTCString()).toBe('Wed, 25 Dec 1991 12:12:59 GMT');

You need to be able to fake the time zone so the tests work always.

**Comment by jlong4096** [comment]
Tests are passing now.
